###
POST http://localhost:3000/Create
Content-Type: application/json

{
    "username": "Weee",
    "password": "0000",
    "name": "we",
    "email": "we@gmail.com"
}

###
GET http://localhost:3000/Read
Content-Type: application/json

{
    "username":"Weee"
}

###
PATCH http://localhost:3000/Update
Content-Type: application/json

{
    "username":"Weee",
    "password":"000000"
}

###
DELETE http://localhost:3000/Delete
Content-Type: application/json

{
    "username":"Weee"
}
